### ISSUE TITLE
Report Generation Does Not Work

### ISSUE THREAD

**Issue by utk-dev** [utk-dev/AttendanceV2#2]
1. For a `TYPE::TEACHER` the generated class report shows wrong percentages.
2. For a `TYPE::MODERATOR` the generated class report gets stuck and does not show anything, nor does it release the cursor for next operation.

**Comment by utk-dev** [comment]
Report gets saved properly..
If you print the attendance file (e.g. `TC000`), it displays all the data correctly.

**Comment by utk-dev** [comment]
So the problem must be in reading the file, or, specifically
`generateClassReportPercentage()`
`generateIndividualReportPercentage()`

**Comment by ronit9586** [comment]
i fixed this bug in latest commit.

**Comment by utk-dev** [comment]
Reports of teachers are displayed one below other (initially we intended to make it horizontal), which is fine. I have checked your commit and it has fixed both functions.
