### ISSUE TITLE
Turning off password echo

### ISSUE THREAD

**Issue by utk-dev** [utk-dev/AttendanceV2#5]
Password echo needs to be turned off. While it is evident that this feature request is not possible with the current framework and will require the curses libraries. Thus, currently this exists as a feature request instead of `invalid` tag.

**Comment by utk-dev** [comment]
Three ways of implementing this, in my opinion, in it's current scope are:

1. Using `termios.h` to change `termios::c_lflag` manually using `ECHO` macro. [difficult/linux only/always works]
2. Using `getpass()` from `unistd.h`. [easy/linux only/obsolete]
3. Using 'curses' library to turn on and off terminal echo.  [medium/cross-platform/separate installation required]

**Comment by arnav127** [comment]
I want to contribute to this by using the ncurses library, it seems to be the best option as it is cross platform, but at the expense of seperate installation. This exta installation can be avoided by releasing a binary which is static linked to the curses lib, thus removing the need for installing curses.

**Comment by utk-dev** [comment]
@arnav127 This is great! Although, I'd appreciate if we add a couple of lines around your function like this:

```cpp
std::string getpass(const char *prompt)     //using the ncurses library
{
  initscr(); // <----- initialise ncurses screen
  erase();   // <----- erase anything leftover from previous outputs on the terminal
  printw(prompt);
  noecho();  // disable character echoing

  char buff[200];       // <--------- buffer size: 200 (Password can be that long - or so does the USER class definition say!)
  getnstr(buff,sizeof(buff));

  echo(); // enable character echoing again
  endwin();              // <---------- go back to the main screen
  return std::string(buff);    // <---------- be explicit about the conversion
}
```
Thanks for your contribution! I apologise for all this undocumented mess and absolutely no organisation in the code.

**Comment by arnav127** [comment]
Thanks @utk-dev for the guidance, I will make the necessary changes to the code and commit it to the pull request.

**Comment by ronit9586** [comment]
ohh, Well done @arnav127.
