### ISSUE TITLE
Date is not displayed correctly in attendance

### ISSUE THREAD

**Issue by ronit9586** [utk-dev/AttendanceV2#8]
date is not formatted correctly. e.g if date is 19-1-2020 then it will show as 19-0-120. that's because month index is start from 0 and year is start form 1900 in `<ctime>`  library.

**Comment by utk-dev** [comment]
I have pinpointed the issue to the following function segment:
**sources/controller/view.cpp**
```cpp
void takeAttendance(USER& teacher)
{
    ....
    std::cout << "\n\nATTENDANCE for " << d.getToday().day << "-" << d.getToday().month << "-" << d.getToday().year << "\n\n";
    ....
}
```

I'm going to add 1 to `g.getToday().month` and add 1900 to `g.getToday().year` as per your suggestion, and commit it.

**Comment by utk-dev** [comment]
- [ ] Fixed the bug.
